### ISSUE TITLE
Current ipv6 implementation doesn't account for interface

### ISSUE THREAD

**Issue by R9295** [multiformats/js-multiaddr#134]
Suppose this is my following multiaddr string:
```
/ip6/fe80::ba27:ebff:fecd:680b%wlp2s0/tcp/5001/p2p/QmVCTgLguTMHTAHKfxQSmML4nUgm33tMrWYKMGxyXeHsVn
```
After parsing, the host should be
```
fe80::ba27:ebff:fecd:680b%wlp2s0
```
but the interface and the ``%`` is omitted. 

This means that ipv6 link/local addresses are not parsed correctly.
This also creates issues with ``libp2p-tcp``, when attempting to bootstrap a node with a local "neighbor node" as the interface is omitted when converting the string to a multiaddr object.

I've started working on a fix, and will hopefully have a pull request soon, just thought of creating an issue before in case anyone else runs into this

See:
https://github.com/libp2p/js-libp2p-bootstrap/issues/105

**Comment by JonathanLorimer** [comment]
Just wanted to ask a question to clarify. I noticed in the protocols.csv that there is a `ip6zone` with multiaddr code 42. I am pretty sure the `%` syntax is part of that addr format. In which case you would have to prefix that address with `ip6zone` instead. It seems that this library doesn't support `ip6zone` anyways, so the issue is still valid, but just wanted to make that clarification.
