### ISSUE TITLE
Make multiaddr extensible on the fly

### ISSUE THREAD

**Issue by daviddias** [multiformats/js-multiaddr#22]
Currently, we have to add a protocol to protocol.js file so that it can be valid multiaddr and constructed by the module. This is ok for all of the transports that are standard (TCP, HTTP, QUIC, etc), but for new protocols that are beta, or simply used in the domain of libp2p or another, we don't have a way to extend multiaddr.

We could have a primitive for 'add new protocol', the tricky part is that multiaddr is used in several points and comparing to go-multiaddr, js-multiaddr gets scoped per module. A typical solution for this would be to Inject the multiaddr dependency, however, that would be very cumbersome to have to DI the DI each time a different part in the code adds another multiaddr.

Several options to solve this have crossed my mind, but I couldn't really figure out a clean and elegant way that would work in the browser and in Node.js.

The intermediate solution is to update this module with any protocol that we need to use in our application.

**Comment by pgte** [comment]
I don't see any harm in changing this in the module scope:

```js
const Multiaddr = require('multiaddr')
Multiaddr.addProto('blah', code, length)
const add = Multiaddr('/ip4/127.0.0.1/tcp/8023/blah/yeah')
```

Do you?

**Comment by pgte** [comment]
Only if you're going to use different instances of this package, (in which case I see why you're mentioning the need for DI).
But the code above suits my use case...

**Comment by diasdavid** [comment]
Inside libp2p, we have multiaddr as a dep everywhere and as long as we have it updated to latest version, module scope should work well for the cases where we update the default table. It is still a PITA if we miss one (finding why it is failing) and if consumers of the libp2p stack don't update their extensions as well.

One idea would be to set a env var pointing to the same table, so that all the Multiaddr instances manipulate the same table.

That being said, we definitely want to have an API to extend the multiaddr table. Following our side channel chat, here is what seems like a good API:

- `Multiaddr.table.add(name, code, size)`
- `Multiaddr.table.get(nameOrCode)`
- `Multiaddr.table.extend(<table-to-be-merged>)`
- `Multiaddr.table.replace(<whole-new-table>)`
- `Multiaddr.table.rm(nameOrCode)`

**Comment by pgte** [comment]
Now looking at the code, I an issue with the default encoding.
The default is `hex` (in [this line](https://github.com/multiformats/js-multiaddr/blob/0f3967873341055eb1e0e9703b348372cb932806/src/convert.js#L55)).

Where is this being used? Could we default to a more general `utf8` and specify `hex` for the cases that need them?

Also, should we support other encodings for protocol extensions? (I'd say `utf8` is generic enough (even though some space may potentially be wasted for these protocols))..

**Comment by diasdavid** [comment]
Seems that is leftovers or code that was never really used, since all the supported protocols were being handled. 

@jbenet wanna chime in on the decision you had made for default to hex?

@pgte independently of the default, we should add an option toString and toBuffer funcs to the `Multiaddr.table.add(name, code, size)`, so that multiple encodings are supported.

**Comment by parkan** [comment]
+1 for this while https://github.com/multiformats/multiaddr/pull/27 is pending

**Comment by kumavis** [comment]
:+1: for this feature

**Comment by bugeats** [comment]
@daviddias do you still feel good about this API?

> * `Multiaddr.table.add(name, code, size)`
> * `Multiaddr.table.get(nameOrCode)`
> * `Multiaddr.table.extend(<table-to-be-merged>)`
> * `Multiaddr.table.replace(<whole-new-table>)`
> * `Multiaddr.table.rm(nameOrCode)`

I'm new to the codebase, but I'd like to solve this issue.  With that in mind, my naive take is that immutably creating a new instance every time you modify the table would solve the issue of scoping the custom state. You just have a `my-multiaddr.js` with your extensions that you can reference. As you migrate a code base to use new protocols, you reference your extended instance instead of the global one.

Can you tell me why it was decided to make `Multiaddr` global in the first place? It will help me understand how to propose a good API.

**Comment by carsonfarmer** [comment]
Our team also really needs this functionality, so very pleased to see @bugeats interested in tackling this. I would be happy to provide assistance on this. We're happy with instance-level modifications as well. The real issue seems to be with convert, where the default hex encoding seems problematic? For backward compatibility, something clever might have to happen there?

**Comment by daviddias** [comment]
> Can you tell me why it was decided to make Multiaddr global in the first place? It will help me understand how to propose a good API.

The trick is that it is not. If the Multiaddr package was a singleton and guaranteed to be a singleton, we could then provide an API like the one you propose and patch the list of codecs on the fly.

This is more of a JavaScript package management problem than a multiaddr/ipfs problem. If two modules depend on two multiaddr versions that don't match on the semver, npm/yarn won't dedup the module (which is good) and that will yield at least one multiaddr instance for each version that got installed on the dependency tree. This translated that in order to properly patch the multiaddr with a new protocol, you would have to chase all those instances and patch all of them simultaneously.

I believe that in order to ensure to a singleton like object exists and it is mutated for all the other modules that use it, the only sound way to do it is through dependency injection from js-ipfs all the way to js-libp2p and all the modules that use in libp2p, so that they all share the same reference. 

The hex issue https://github.com/multiformats/js-multiaddr/issues/22#issuecomment-250402844 is a secondary problem to this thread.

**Comment by carsonfarmer** [comment]
Seems like maybe 525268b3727bb9413e58322059d6ece7ec65e7f7 "resolves" this ;)
