### ISSUE TITLE
Reference to non-existent js file from ts

### ISSUE THREAD

**Issue by dao** [multiformats/js-multiaddr#304]
**Describe the bug**
In https://github.com/multiformats/js-multiaddr/blob/master/src/convert.ts I see:

`import { getProtocol } from './protocols-table.js'`

Stepping out to the directory view, there is no `protocols-table.js`. There is, however, `protocols-table.ts`.

**Comment by p-shahi** [comment]
@maschad will take this on

**Comment by maschad** [comment]
This is because [the build tool (aegir)](https://github.com/ipfs/aegir)  transpiles ESM from TS  when the **build** is generated, (in the `./dist` folder)  and relative import paths need full extensions (e.g we have to write `import "./foo.js"` instead of `import "./foo"` ). You can see a similar example [here](https://github.com/multiformats/js-multiaddr/blob/master/src/index.ts#L15-L16) or [here](https://github.com/multiformats/js-multiaddr/blob/master/src/protocols-table.ts#L1) 

For more info see: https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by achingbrain** [comment]
@dao I think this is functioning as expected.  Are you seeing an error message or stack trace?  If you are, can you please share the stack trace or repro repo.

**Comment by achingbrain** [comment]
Closing due to lack of response. Please reopen if you can provide the requested information.
